/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Class.choNgoiClass;
import Class.hoaDonClass;
import Class.khachHangClass;
import Class.lichChieuClass;
import Class.nVienClass;
import Class.veClass;
import Control.BanveCtr;
import Control.ClientCtr;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenlink
 */
public class hoadonFrm extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    DefaultTableModel tb2;
    /**
     * Creates new form hoadonFrm
     */
    private ArrayList<khachHangClass> list;
    public hoaDonClass hdon = new hoaDonClass();
    SearchFilmFrm sff = new SearchFilmFrm();
    private float tong = 0;
    public hoadonFrm() throws ParseException, SQLException {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        loginFrm loFrm = new loginFrm();
        tableModel = (DefaultTableModel) tblkHang.getModel();
        tb2 = (DefaultTableModel) tblhoadon.getModel();
        
        ngay.setText("Ngày: " + java.time.LocalDate.now().toString());
        tenNV.setText("Nhân viên bán vé: " + loFrm.nvClass.getTenNV());
//        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        hdon.setNgay(java.sql.Date.valueOf(LocalDate.now()));
        nVienClass nv = new nVienClass();
        nv.setMaNV(loFrm.nvClass.getMaNV());
        hdon.setnVien(nv);
        
        loadtblHoadon();
    }
    public void tblkHangClicked(){
        int Row = tblkHang.getSelectedRow();
        khachHangClass kh = new khachHangClass();
        kh.setMaKH((int) tblkHang.getValueAt(Row, 0));
        hdon.setKHang(kh);

        System.out.println(hdon.KHang.getMaKH());
//        System.out.println(tblkHang.getValueAt(Row, 0));
        tenKH.setText("Tên khách hàng: " + (String) tblkHang.getValueAt(Row, 1));
        Sdt.setText("Số điện thoại:" + (String) tblkHang.getValueAt(Row, 2));
        email.setText("Email: " + (String) tblkHang.getValueAt(Row, 3));
        diachi.setText("Địa chỉ: " + (String) tblkHang.getValueAt(Row, 4));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkHang = new javax.swing.JTable();
        tenNV = new javax.swing.JLabel();
        ngay = new javax.swing.JLabel();
        tenKH = new javax.swing.JLabel();
        Sdt = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        diachi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblhoadon = new javax.swing.JTable();
        tongtien = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HÓA ĐƠN");

        jLabel2.setText("Tên khách hàng");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblkHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên khách hàng", "Số điện thoại", "Email", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tblkHang);

        tblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Phim", "Giờ chiếu", "Phòng chiếu", "Giá tiền", "Ghi chú"
            }
        ));
        jScrollPane2.setViewportView(tblhoadon);
        if (tblhoadon.getColumnModel().getColumnCount() > 0) {
            tblhoadon.getColumnModel().getColumn(0).setMinWidth(50);
            tblhoadon.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblhoadon.getColumnModel().getColumn(0).setMaxWidth(50);
            tblhoadon.getColumnModel().getColumn(1).setMinWidth(120);
            tblhoadon.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblhoadon.getColumnModel().getColumn(1).setMaxWidth(120);
            tblhoadon.getColumnModel().getColumn(2).setMinWidth(90);
            tblhoadon.getColumnModel().getColumn(2).setPreferredWidth(90);
            tblhoadon.getColumnModel().getColumn(2).setMaxWidth(90);
            tblhoadon.getColumnModel().getColumn(3).setMinWidth(90);
            tblhoadon.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblhoadon.getColumnModel().getColumn(3).setMaxWidth(90);
            tblhoadon.getColumnModel().getColumn(4).setMinWidth(90);
            tblhoadon.getColumnModel().getColumn(4).setPreferredWidth(90);
            tblhoadon.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tenKH)
                                    .addComponent(Sdt))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tenNV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ngay))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(diachi))
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnSelect))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(tongtien)
                                    .addGap(135, 135, 135))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(btnCancel))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelect)
                    .addComponent(btnAdd))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenNV)
                    .addComponent(ngay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tenKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sdt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(diachi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tongtien)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadtblHoadon() throws SQLException{
        veFrm vf = new veFrm();
        ArrayList<choNgoiClass> listcn = vf.listCngoi;
        for (int i = 0; i < listcn.size(); i++) {
            if (listcn.get(i).getLoai().equals("Thuong")) {
                tb2.insertRow(i, new Object[]{i+1,sff.tenphim,sff.thoigian.toString(),sff.tenphong,45000,"Ghế: " + listcn.get(i).getHang() + listcn.get(i).getCot()});
                tong += 45000;
            }else{
                tb2.insertRow(i, new Object[]{i+1,sff.tenphim,sff.thoigian.toString(),sff.tenphong,55000,"Ghế: " + listcn.get(i).getHang() + listcn.get(i).getCot()});
                tong += 55000;
            }
        }
        tongtien.setText("Tổng tiền: " + tong);
    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (!txtKey.getText().equals("")) {
            String key = txtKey.getText();
            ClientCtr clientCtr = new ClientCtr();
            try {
                list = clientCtr.SearchClient(key);
                for(int i = 0;i < list.size();i++){
                    tableModel.insertRow(i, new Object[]{list.get(i).getMaKH(), list.get(i).getTenKH(), list.get(i).getSdt(), list.get(i).getEmail(), list.get(i).getDiachi()});
                }
            } catch (SQLException ex) {
                Logger.getLogger(hoadonFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        tblkHangClicked();
        
        BanveCtr bc = new BanveCtr();
        try {
            bc.addHoadon(hdon);
        } catch (SQLException ex) {
            Logger.getLogger(hoadonFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funcFrm().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        try {
            BanveCtr bc = new BanveCtr();
            veFrm vf = new veFrm();
            ArrayList<choNgoiClass> listcn = vf.listCngoi;
            for (int i = 0; i < listcn.size(); i++) {
                veClass ve1 = new veClass();
                if (listcn.get(i).getLoai().equals("Thuong")) {
                    ve1.setGia(45000);
                    
                    choNgoiClass cn = new choNgoiClass();
                    cn.setMaCho(listcn.get(i).getMaCho());
                    ve1.setCngoi(cn);
                    
                    lichChieuClass lc = new lichChieuClass();
                    lc.setMalich(sff.malich);
                    ve1.setLchieu(lc);
                    
//                    hoaDonClass hd = new hoaDonClass();
                    hdon.setMaHD(bc.getLastIDHD());
                    ve1.setHdon(hdon);
                    System.out.println(ve1.getGia() + "-" + (int)ve1.cngoi.getMaCho() + "-" + (int)ve1.lchieu.getMalich() + "--" + (int)ve1.hdon.getMaHD());
                    bc.addVe(ve1);
//                    System.out.println(ve1.toString());
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(hoadonFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClientFrm().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoadonFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoadonFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoadonFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoadonFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                try {
//                    new hoadonFrm().setVisible(true);
//                } catch (ParseException ex) {
//                    Logger.getLogger(hoadonFrm.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (SQLException ex) {
//                    Logger.getLogger(hoadonFrm.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sdt;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel diachi;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel ngay;
    private javax.swing.JTable tblhoadon;
    private javax.swing.JTable tblkHang;
    private javax.swing.JLabel tenKH;
    private javax.swing.JLabel tenNV;
    private javax.swing.JLabel tongtien;
    private javax.swing.JTextField txtKey;
    // End of variables declaration//GEN-END:variables
}
