/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Class.choNgoiClass;
import Control.BanveCtr;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenlink
 */
public class veFrm extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    /**
     * Creates new form veFrm
     */
    String[] hang = {"A","B","C","D","E"};
    private ArrayList<choNgoiClass> list;
    public static ArrayList<choNgoiClass> listCngoi;
    private boolean run = true;
    
    SearchFilmFrm sff = new SearchFilmFrm();
    
    public veFrm() throws SQLException {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        tableModel = (DefaultTableModel) tblchongoi.getModel();
        
        info.setText("Phim: " + sff.tenphim + " - Thời lượng: " + sff.thoiluong.toString() + " - Thời gian: " + sff.thoigian.toString() + " - Ngày: " + sff.ngay.toString() + " - Phòng chiếu: " + sff.tenphong);

        setGhetrong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        info = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblchongoi = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblchongoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true)},
                { new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true)},
                { new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true)},
                { new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true)},
                { new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true)}
            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblchongoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchongoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblchongoi);
        if (tblchongoi.getColumnModel().getColumnCount() > 0) {
            tblchongoi.getColumnModel().getColumn(0).setMinWidth(50);
            tblchongoi.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblchongoi.getColumnModel().getColumn(0).setMaxWidth(50);
            tblchongoi.getColumnModel().getColumn(1).setMinWidth(50);
            tblchongoi.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblchongoi.getColumnModel().getColumn(1).setMaxWidth(50);
            tblchongoi.getColumnModel().getColumn(2).setMinWidth(50);
            tblchongoi.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblchongoi.getColumnModel().getColumn(2).setMaxWidth(50);
            tblchongoi.getColumnModel().getColumn(3).setMinWidth(50);
            tblchongoi.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblchongoi.getColumnModel().getColumn(3).setMaxWidth(50);
            tblchongoi.getColumnModel().getColumn(4).setMinWidth(50);
            tblchongoi.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblchongoi.getColumnModel().getColumn(4).setMaxWidth(50);
            tblchongoi.getColumnModel().getColumn(5).setMinWidth(50);
            tblchongoi.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblchongoi.getColumnModel().getColumn(5).setMaxWidth(50);
            tblchongoi.getColumnModel().getColumn(6).setMinWidth(50);
            tblchongoi.getColumnModel().getColumn(6).setPreferredWidth(50);
            tblchongoi.getColumnModel().getColumn(6).setMaxWidth(50);
        }

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Màn chiếu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Vé đã được chọn");

        jCheckBox2.setText("Vé chưa được chọn");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(info))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info)
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
            if(listCngoi.isEmpty() == false){
                 this.dispose();
                  java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                try {
                    new hoadonFrm().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(hoadonFrm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(veFrm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            }); 
            } else{
                JOptionPane.showConfirmDialog(this, "slkjf");
            }
           
           
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void tblchongoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchongoiMouseClicked
       tblchongoiClicked();
    }//GEN-LAST:event_tblchongoiMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new funcFrm().setVisible(true);
                        }
                     });
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setGhetrong() throws SQLException{
        BanveCtr bc = new BanveCtr();
        list = bc.loadGheTrong(sff.malich, sff.maphong);
        for (int i = 0; i < list.size(); i++) {
            System.out.println(list.get(i).getMaCho() + " " + list.get(i).getHang().toUpperCase() + " " + list.get(i).getCot());
            switch (list.get(i).getHang().toUpperCase()){
                case "A":{
                    tableModel.setValueAt(false, 0, list.get(i).getCot() - 1);
                    break;
                }
                case "B":{
                    tableModel.setValueAt(false, 1, list.get(i).getCot() - 1);
                    break;
                }
                case "C":{
                    tableModel.setValueAt(false, 2, list.get(i).getCot() - 1);
                    break;
                }
                case "D":{
                    tableModel.setValueAt(false, 3, list.get(i).getCot() - 1);
                    break;
                }
                case "E":{
                    tableModel.setValueAt(false, 3, list.get(i).getCot() - 1);
                    break;
                }
            }
        }
    }
    
    public void tblchongoiClicked(){
        String row = hang[tblchongoi.getSelectedRow()];
        int col = tblchongoi.getSelectedColumn() + 1;
        BanveCtr bc = new BanveCtr();
        try {
            listCngoi = bc.getList(row, col, sff.maphong);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ghế được chọn không được để trống");
        }
        
        for (int i = 0; i < listCngoi.size(); i++) {
            System.out.println(listCngoi.get(i).getMaCho() + "---" +listCngoi.get(i).getHang().toUpperCase()+ listCngoi.get(i).getCot() + "---" + listCngoi.get(i).getLoai().toString());           
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(veFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(veFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(veFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(veFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new veFrm().setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(veFrm.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel info;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblchongoi;
    // End of variables declaration//GEN-END:variables
}
